// Generated by OrchestKit Claude Plugin
// Created: 2026-07-03

import { getAllTerms } from "@/data/loaders";
import { NextRequest, NextResponse } from "next/server";

export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const page = Math.max(1, parseInt(searchParams.get("page") || "1", 10));
    const pageSize = Math.min(
      100,
      Math.max(1, parseInt(searchParams.get("pageSize") || "12", 10))
    );
    const search = searchParams.get("search") || "";

    const result = await getAllTerms(page, pageSize, search);
    return NextResponse.json(result);
  } catch (error) {
    console.error("Error fetching terms:", error);
    return NextResponse.json(
      { error: "Failed to fetch terms" },
      { status: 500 }
    );
  }
}
