// Generated by OrchestKit Claude Plugin
// Created: 2026-07-03

import { getPlaylistVideosPaginated } from "@/data/loaders";
import { NextRequest, NextResponse } from "next/server";

export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const playlistId = parseInt(searchParams.get("playlistId") || "", 10);
    const page = Math.max(1, parseInt(searchParams.get("page") || "1", 10));
    const pageSize = Math.min(
      100,
      Math.max(1, parseInt(searchParams.get("pageSize") || "12", 10))
    );

    if (!playlistId || isNaN(playlistId)) {
      return NextResponse.json(
        { error: "playlistId is required and must be a number" },
        { status: 400 }
      );
    }

    const videos = await getPlaylistVideosPaginated(playlistId, page, pageSize);
    return NextResponse.json(videos);
  } catch (error) {
    console.error("Error fetching playlist videos:", error);
    return NextResponse.json(
      { error: "Failed to fetch playlist videos" },
      { status: 500 }
    );
  }
}
