// Generated by OrchestKit Claude Plugin
// Created: 2026-07-03

import { getResponsaBySlug } from "@/data/loaders";
import { NextRequest, NextResponse } from "next/server";

export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const slug = searchParams.get("slug");

    if (!slug) {
      return NextResponse.json(
        { error: "slug parameter is required" },
        { status: 400 }
      );
    }

    const result = await getResponsaBySlug(slug);
    return NextResponse.json(result);
  } catch (error) {
    console.error("Error fetching responsa:", error);
    return NextResponse.json(
      { error: "Failed to fetch responsa" },
      { status: 500 }
    );
  }
}
