// Generated by OrchestKit Claude Plugin
// Created: 2026-07-03

import { getWritingsPaginated } from "@/data/loaders";
import { NextRequest, NextResponse } from "next/server";

export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const page = Math.max(1, parseInt(searchParams.get("page") || "1", 10));
    const pageSize = Math.min(
      100,
      Math.max(1, parseInt(searchParams.get("pageSize") || "12", 10))
    );
    const typeFilter = (searchParams.get("type") as "all" | "book" | "article") || "all";
    const search = searchParams.get("search") || undefined;
    const sortBy = (searchParams.get("sortBy") as "priority" | "popular") || "priority";

    const result = await getWritingsPaginated(page, pageSize, typeFilter, search, sortBy);
    return NextResponse.json(result);
  } catch (error) {
    console.error("Error fetching writings:", error);
    return NextResponse.json(
      { error: "Failed to fetch writings" },
      { status: 500 }
    );
  }
}
