// Generated by OrchestKit Claude Plugin
// Created: 2026-02-25

import { revalidatePath } from "next/cache";
import { NextRequest, NextResponse } from "next/server";

// Strapi webhook: POST /api/revalidate?secret=<REVALIDATE_SECRET>
// Body (from Strapi lifecycle hook or webhook): { model, entry }
export async function POST(request: NextRequest) {
  const secret = request.nextUrl.searchParams.get("secret");

  if (secret !== process.env.REVALIDATE_SECRET) {
    return NextResponse.json({ message: "Invalid token" }, { status: 401 });
  }

  try {
    const body = await request.json();
    const model: string = body?.model ?? body?.event ?? "";
    const entry = body?.entry ?? body?.data ?? {};

    if (model.includes("comment") || model.includes("thread")) {
      // Revalidate the specific responsa or blog page the comment belongs to
      const responsaSlug: string | undefined = entry?.responsaSlug;
      const blogSlug: string | undefined = entry?.blogSlug;

      if (responsaSlug) revalidatePath(`/responsa/${responsaSlug}`);
      if (blogSlug) revalidatePath(`/blog/${blogSlug}`);
    } else if (model.includes("responsa")) {
      const slug: string | undefined = entry?.slug;
      if (slug) {
        revalidatePath(`/responsa/${slug}`);
      }
      revalidatePath("/responsa");
    } else if (model.includes("writing")) {
      const slug: string | undefined = entry?.slug;
      if (slug) {
        revalidatePath(`/writings/${slug}`);
      }
      revalidatePath("/writings");
    } else if (model.includes("playlist")) {
      const slug: string | undefined = entry?.slug ?? entry?.youtubeId;
      if (slug) {
        revalidatePath(`/playlists/${slug}`);
      }
      revalidatePath("/playlists");
    } else if (model.includes("video")) {
      const playlistSlug: string | undefined =
        entry?.playlist?.slug ?? entry?.playlist?.youtubeId;
      const videoSlug: string | undefined = entry?.slug ?? entry?.videoId;
      if (playlistSlug && videoSlug) {
        revalidatePath(`/playlists/${playlistSlug}/${videoSlug}`);
      }
      if (playlistSlug) {
        revalidatePath(`/playlists/${playlistSlug}`);
      }
      revalidatePath("/playlists");
    } else if (model.includes("blog")) {
      const slug: string | undefined = entry?.slug;
      if (slug) {
        revalidatePath(`/blog/${slug}`);
      }
      revalidatePath("/blog");
    } else if (model.includes("term")) {
      const slug: string | undefined = entry?.slug;
      if (slug) {
        revalidatePath(`/terms/${slug}`);
      }
      revalidatePath("/terms");
    } else {
      // Generic full-site revalidation as fallback
      revalidatePath("/", "layout");
    }

    return NextResponse.json({ revalidated: true });
  } catch {
    return NextResponse.json({ message: "Error revalidating" }, { status: 500 });
  }
}
