// Generated by OrchestKit Claude Plugin
// Created: 2026-07-03

import { searchContent } from "@/data/services";
import { SearchFilters } from "@/types";
import { NextRequest, NextResponse } from "next/server";

const VALID_CONTENT_TYPES = ["all", "blog", "video", "playlist", "responsa", "writing"] as const;

export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const contentTypeParam = searchParams.get("contentType") || "all";

    // Validate content type
    const contentType = VALID_CONTENT_TYPES.includes(contentTypeParam as any)
      ? (contentTypeParam as "all" | "blog" | "video" | "playlist" | "responsa" | "writing")
      : "all";

    const filters: SearchFilters = {
      query: searchParams.get("query") || undefined,
      contentType,
      category: searchParams.get("category") || undefined,
      sort: searchParams.getAll("sort"),
    };

    const response = await searchContent(filters);
    return NextResponse.json(response);
  } catch (error) {
    console.error("Error searching content:", error);
    return NextResponse.json(
      { error: "Failed to search content" },
      { status: 500 }
    );
  }
}
