// Generated by OrchestKit Claude Plugin
// Created: 2026-07-03

import { getEmailIssueCategories } from "@/data/loaders";
import { NextResponse } from "next/server";

export async function GET() {
  try {
    const result = await getEmailIssueCategories();
    return NextResponse.json(result);
  } catch (error) {
    console.error("Error fetching email issue categories:", error);
    return NextResponse.json(
      { error: "Failed to fetch email issue categories" },
      { status: 500 }
    );
  }
}
