// Generated by OrchestKit Claude Plugin
// Created: 2026-07-03

import { getAllCategories } from "@/data/services";
import { NextResponse } from "next/server";

export async function GET() {
  try {
    const categories = await getAllCategories();
    return NextResponse.json(categories);
  } catch (error) {
    console.error("Error fetching categories:", error);
    return NextResponse.json(
      { error: "Failed to fetch categories" },
      { status: 500 }
    );
  }
}
